### ISSUE TITLE
FEATURE: Customizable Styling

### ISSUE THREAD

**Issue by roderiano** [roderiano/django-blog#7]
**Is your feature request related to a problem? Please describe.**
Create dynamic styling of bootstrap using a css file.

This enhancement introduces a more customizable visual style for the Django Blog project. Users now have the flexibility to tailor the appearance of the blog by adjusting custom CSS variables. The following key customizations are available:

**Customizable CSS Variables**
--custom-primary: Customize the primary color for buttons.
--custom-secondary: Personalize the secondary color for buttons.
--custom-body-color: Adjust the background color of the body.
--custom-main-color: Set the main text color.
--custom-navbar-color: Define the background color of the navigation bar.

**How to Use**

**Primary and Secondary Colors:**
Utilize --custom-primary and --custom-secondary for customizing button colors.

```css
.btn-primary {
    background-color: var(--custom-primary);
    border-color: var(--custom-primary);
    color: #fff;
}

.btn-secondary {
    background-color: var(--custom-secondary);
    border-color: var(--custom-secondary);
    color: #fff;
}

```
**Navigation Bar:**
Customize the navigation bar color using --custom-navbar-color.

```css
.navbar {
    background-color: var(--custom-navbar-color);
}
```

**Body and Main Text Color:**
Adjust the background color of the body and the main text color using --custom-body-color and --custom-main-color, respectively.

```css
body {
    color: var(--custom-main-color);
    background-color: var(--custom-body-color);
}
```
**Related Files**
style.css: Introduces the custom CSS variables and their usage.
